var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":187,"id":26,"methods":[{"el":45,"sc":3,"sl":41},{"el":54,"sc":3,"sl":47},{"el":66,"sc":3,"sl":56},{"el":86,"sc":3,"sl":68},{"el":106,"sc":3,"sl":88},{"el":134,"sc":3,"sl":108},{"el":164,"sc":3,"sl":136},{"el":186,"sc":3,"sl":166}],"name":"RepositoriesTests","sl":30}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":88}],"name":"shouldQueryEntity","pass":true,"statements":[{"sl":91},{"sl":94},{"sl":98},{"sl":101},{"sl":105}]},"test_1":{"methods":[{"sl":68}],"name":"shouldRetrieveEntity","pass":true,"statements":[{"sl":71},{"sl":75},{"sl":76},{"sl":79},{"sl":83},{"sl":84}]},"test_2":{"methods":[{"sl":136}],"name":"shouldPartiallyUpdateEntity","pass":true,"statements":[{"sl":139},{"sl":143},{"sl":145},{"sl":148},{"sl":152},{"sl":156},{"sl":158},{"sl":161}]},"test_3":{"methods":[{"sl":108}],"name":"shouldUpdateEntity","pass":true,"statements":[{"sl":111},{"sl":115},{"sl":117},{"sl":120},{"sl":123},{"sl":127},{"sl":129},{"sl":132}]},"test_4":{"methods":[{"sl":56}],"name":"shouldCreateEntity","pass":true,"statements":[{"sl":59},{"sl":63}]},"test_5":{"methods":[{"sl":166}],"name":"shouldDeleteEntity","pass":true,"statements":[{"sl":169},{"sl":173},{"sl":174},{"sl":176},{"sl":178},{"sl":182},{"sl":183},{"sl":185}]},"test_6":{"methods":[{"sl":47}],"name":"shouldReturnRepositoryIndex","pass":true,"statements":[{"sl":50}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [6], [], [], [6], [], [], [], [], [], [4], [], [], [4], [], [], [], [4], [], [], [], [], [1], [], [], [1], [], [], [], [1], [1], [], [], [1], [], [], [], [1], [1], [], [], [], [0], [], [], [0], [], [], [0], [], [], [], [0], [], [], [0], [], [], [], [0], [], [], [3], [], [], [3], [], [], [], [3], [], [3], [], [], [3], [], [], [3], [], [], [], [3], [], [3], [], [], [3], [], [], [], [2], [], [], [2], [], [], [], [2], [], [2], [], [], [2], [], [], [], [2], [], [], [], [2], [], [2], [], [], [2], [], [], [], [], [5], [], [], [5], [], [], [], [5], [5], [], [5], [], [5], [], [], [], [5], [5], [], [5], [], []]
